---
kind: pipeline
name: update 

steps:
  - name: update_repository
    image: debian:latest
    environment:
      TOKEN:
        from_secret: github_token
    commands:
    - apt-get update
    - apt-get install -y git

    - mkdir -p /drone/ci
    - cd /drone/ci
    
    - git clone https://$TOKEN@github.com/morgrimm/repo.git .
    - git submodule sync
    - git submodule update --init

    - git config credential.helper 'cache --timeout=120'
    - git config user.name 'Drone'
    - git config user.email 'drone'

    - git submodule update --remote --merge pkgs/com.morgrimm.morglyphs
    - git add -A
    - 'git commit -m "chore: Update morglyphs to ${DRONE_TAG}"'
    - git push -q https://$TOKEN@github.com/morgrimm/repo.git master
    when:
      branch: master
trigger:
  event:
  - tag
---
kind: signature
hmac: 1f25c3dc475e5f8f8cda1e0b13da0c1e2d1bde8bcbace9a5a602a48dc0443f30

...
