env_defaults: &env_defaults
  docker:
    - image: debian:stretch-slim
  working_directory: ~/ci

git_install: &git_install
  run:
    name: Install Git
    command: |
      apt-get update
      apt-get install -y git

git_configure_user: &git_configure_user
  run:  
    name: Configure Git user
    command: |  
      git config credential.helper 'cache --timeout=120'
      git config user.name "CircleCI"
      git config user.email "circleci"

git_checkout: &git_checkout
  run:
    name: Checkout source
    command: |
      git clone https://${GITHUB_PERSONAL_TOKEN}@github.com/morgrimm/${REPO}.git .
      git submodule sync
      git submodule update --init
      git checkout ${CIRCLE_BRANCH}

version: 2.1
jobs:
  update_repository:
    <<: *env_defaults
    environment:
      REPO: repo
      PKGPATH: pkgs/com.morgrimm.morglyphs
    steps:
      - *git_install
      - *git_checkout
      - *git_configure_user
      - run: git submodule update --remote --merge ${PKGPATH}
      - run:
          name: Update package
          command: |
            git add -A
            git commit -m "Update morglyphs by CircleCI"
            git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/morgrimm/${REPO}.git ${CIRCLE_BRANCH}

workflows:
  version: 2
  update-repo:
    jobs:
      - update_repository:
          filters:
            branches:
              only: master
            tags:
              only: /^v\d+\.\d+\.\d+$/
